add bloc logic to schedule_screen
UnionPlayerApp/player pull request #14
Opened 2021-04-29 12:49 UTC by LenaTopoleva

2021-04-29 14:50 UTC, chplalex commented on lib/repository/repository.dart
> +class Repository {
1) я предлагаю придерживаться нейминга, которому нас приучили на учёбе - интерфейсы именовать с буквы "I". Т.е. в данном случае, IRepository. Тогда при чтении кода будет сразу понятно, что это не обычный класс, а класс, который будет выполнять функцию интерфейса.
2) И название класса и название метода слишком общие и не отражают их предназначения. При чтении кода совершенно непонятно с какими данными они работают. Давай удлинним, но сделаем более понятными:
IScheduleRepository
Соответственно, класс назовем SchedulerRepositoryImpl
Метод - getSchedulerList
а модельку - SchedulerItem

2021-04-29 16:13 UTC, chplalex commented on lib/screen_schedule/schedule_bloc.dart
> +class ScheduleBloc extends Bloc<ScheduleEvent, ScheduleState> {
тут такие моменты:

1) items в виде свойства класса в данном случае избыточно. Его лучше создать внутри метода mapEventToState в качестве локальной переменной. Кстати, таким образом ты исправишь, заодно, ошибку - ты его не очищаешь при добавлении в него загруженных из репозитория эжлементов. Поэтому при повторной перезагрузке список будет загружаться дублями.
2) По State - у нас возможны такие состояния списка. которые должны по разному отображаться на экране:
"ScheduleLoadAwaitState" (состояние ожидания во время загрузки) список делаем полупрозрачным, отображаем индикатор загрузки
"ScheduleLoadSuccessState" (загрузка прошла успешно) отображаем список
"ScheduleLoadErrorState" (загрузка завершилась ошибкой) отображаем сообщение

я пока никак не пойму, какой стейт мы должны передавать в конструктор блока. Может быть нужно сделать еще один типа ScheduleUknownState - вроде "неопределенный"? или ScheduleStartState - "стартовый"?
3) Event у нас вроде бы один (пока) - фактически это команда на загрузку данных. Она должна генерироваться при старте страницы, а также при её перезагрузке (refresh. Это когда  когда пальцем сверху вниз проводишь для принудительной перегрузке, а также (сделаем это позже) список у нас будет автоматически обновляться ни старте очередной программы). Давай это событие назовем SchedulerLoadEvent

2021-04-29 16:16 UTC, chplalex commented on lib/screen_schedule/schedule_page.dart
> +  Widget build(BuildContext context) {
создание страниц лучше вынести в приватные методы типа _createLoadSuccessPage(), _createLoadErrorPage(), _createLoadAwaitPage() - так получится более наглядно

2021-04-29 16:18 UTC, chplalex commented on lib/screen_schedule/schedule_page.dart
> -class ProgramListItem extends StatelessWidget {
нужно вынести этот класс в отдельный файл

2021-04-29 16:19 UTC, chplalex requested changes
Посмотри пожалуйста мои комментарии.

2021-05-01 16:54 UTC, LenaTopoleva commented on lib/repository/repository.dart
> +class Repository {
готово

2021-05-01 16:57 UTC, LenaTopoleva commented on lib/screen_schedule/schedule_page.dart
> -class ProgramListItem extends StatelessWidget {
этого класс я удалила же вообще, вместо него теперь просто метод _listView, который возвращает виджет списка. Методы перепишу как ты посоветовал, по типу createPage()

2021-05-01 16:59 UTC, LenaTopoleva commented on lib/screen_schedule/schedule_bloc.dart
> +class ScheduleBloc extends Bloc<ScheduleEvent, ScheduleState> {
да, ошибка со списком глупая! спасибо!

2021-05-01 17:38 UTC, LenaTopoleva commented on lib/screen_schedule/schedule_bloc.dart
> +class ScheduleBloc extends Bloc<ScheduleEvent, ScheduleState> {
Мне кажется ScheduleLoadAwaitState вполне подходит для конструктора блока. Блок создается один раз и при первом открытии экрана, нам нужно сразу загрузить список. Поэтому, кмк, еще одно состояние будет лишним.

2021-05-01 17:39 UTC, LenaTopoleva commented on lib/screen_schedule/schedule_bloc.dart
> +class ScheduleBloc extends Bloc<ScheduleEvent, ScheduleState> {
Про ScheduleLoadErrorState даже пока не задумывалась, привыкла решать задачи по мере поступления, пока в репозитории лежит захардкоженный список ошибки быть не может) Я добавлю, конечно

2021-05-03 13:41 UTC, LenaTopoleva commented
Все поправила!

2021-05-03 19:27 UTC, merged