Нарисовала 2 экрана: экран с расписанием и экран обратной связи (схематично). В отдельной папке ui - общие элементы: AppBar и BottomNavigationBar.
UnionPlayerApp/player pull request #5
Opened 2021-04-19 09:07 UTC by LenaTopoleva

Чтобы запустить экран расписания, надо в main.dart заменить код на:

void main() {
  runApp(ScheduleScreen(isPlaying: false));
}

для запуска экрана обратной связи:
 
void main() {
  runApp(FeedbackScreen(isPlaying: false));
}

2021-04-20 08:46 UTC, chplalex commented on lib/feedback_screen/feedback_screen.dart
> +  IconData _appBarIcon = Icons.play_circle_outline;
Предлагаю использовать Icons.play_arrow_rounded и Icons.pause_rounded. Чуть более симпатичные иконки со скругленными углами.

2021-04-20 08:47 UTC, chplalex commented on lib/feedback_screen/feedback_screen.dart
> +        body: SingleChildScrollView(padding: EdgeInsets.all(10.0), child:
child с новой строки

2021-04-20 08:48 UTC, chplalex commented on lib/feedback_screen/feedback_screen.dart
> +        new Form(
new мы не используем

2021-04-20 08:50 UTC, chplalex commented on lib/feedback_screen/feedback_screen.dart
> +              new Text('Ваше имя:', style: TextStyle(fontSize: 20.0),),
попробуй наиболее частно используемые значения. типа fontSize: 20.0 вынести в константы для общего использования. Размеры шрифтов на разных экранах должны быть одинаковыми, а значит устанавливать их нужно через общие коннстанты. По идее должен быть файл с общими паблик константами, для всех экранов и, возмоно, если понадобятся, приватные константы для конкрентых экранов.

2021-04-20 08:52 UTC, chplalex commented on lib/feedback_screen/feedback_screen.dart
> +              new Text('Контактный E-mail:', style: TextStyle(fontSize: 20.0),),
Я еще не добрался, но посмоти, вдруг найдёшь - как решается здесь вопрос с локализацией и. в частности, с локализацией текста. По-хорошему (мы к этому уже привыкли) текст мы делаем на русском и сразу на английском и он подтягивается в зависимости от локализации девайса.

2021-04-20 08:54 UTC, chplalex commented on lib/feedback_screen/feedback_screen.dart
> +                String p = "[a-zA-Z0-9+.\_\%-+]{1,256}@[a-zA-Z0-9][a-zA-Z0-9-]{0,64}(.[a-zA-Z0-9][a-zA-Z0-9-]{0,25})+";
В андроиде были предустановленные шаблоны ввода в EditTextView типа "email" или "password". Нет ли и здесь такого?

2021-04-20 08:59 UTC, chplalex commented on lib/feedback_screen/feedback_screen.dart
> +                  SnackBar(content: Text(text), backgroundColor: color,));
если проверка на заполнение формы не будет выполнена, то переменные text и color не будут инициализированы и, по идее, при создании SnackBar должна произойти ошибка. Нет? Проверь пож. По идее, эти переменные должны инициализироваться и в случае если форма заполнена, и в случае, если форма не заполнена.

2021-04-20 09:03 UTC, chplalex commented on lib/schedule_screen/schedule_screen.dart
> +
По-хорошему, нужен класс ProgramsRepository. B у него должен быть метод get() возвращающий List<ProgramItem>. Создай его пож.  в отдельном файле и в отдельной папке repository. Позже мы добавим его внедрение через DI. Ну и перепишем его в соответствии с ТЗ через чтение и разбор XML. Этим занимается Антон.

2021-04-20 09:08 UTC, chplalex commented on lib/schedule_screen/schedule_screen.dart
> +  ProgramListItem(this._title, this._text, this._startTime, {required String imageUrl}) {
Когда будет создан датакласс ProgramItem, то логичнее в конструтор передавать его.

2021-04-20 09:11 UTC, chplalex commented on lib/schedule_screen/schedule_screen.dart
> +    if (_imageUrl != null && _imageUrl != '') image = Image.network(_imageUrl, width: 100.0, height: 100.0, fit: BoxFit.cover);
Вроде бы в конструкторе "required String imageUrl" как я понимаю, это означает, что imageUrl ненуллабельный. Тогда зачем проверка на null? И, честно говоря, я не понял, почему это поле ты не передаешь как и все остальные через this._imageUrl ?

2021-04-20 09:14 UTC, chplalex commented on lib/schedule_screen/schedule_screen.dart
> +                    new Expanded(child:new Text(_title, style: new TextStyle(fontSize: 17.0), softWrap: true, textAlign: TextAlign.start, maxLines: 1, overflow: TextOverflow.ellipsis,)),
А вот такая идея - вынести создание стилей или в отдельные классы (типа HeaderTextStyle, BodyTextStyle), или в отдельнвые фабрики (типа TextStyle createHeaderTextStyle(), TextStyle createBodyTextStyle). Это 1) позволит в одном месте сосредоточить код, который отвечает за стилизацию изображения и 2) улучшит читабельность.

2021-04-20 09:16 UTC, chplalex commented on lib/feedback_screen/feedback_screen.dart
> +  void _onButtonAppBarTapped(){
Общее замечание/предложение - структурировать код в соответствии с BLoC паттерном.

2021-04-20 09:17 UTC, chplalex requested changes
Я оставил по тексту ряд замечаний и соображений, посмотри пожалуйста.

2021-04-25 02:54 UTC, LenaTopoleva commented on lib/feedback_screen/feedback_screen.dart
> +  IconData _appBarIcon = Icons.play_circle_outline;
+

2021-04-25 02:55 UTC, LenaTopoleva commented on lib/feedback_screen/feedback_screen.dart
> +  IconData _appBarIcon = Icons.play_circle_outline;
готово

2021-04-25 02:55 UTC, LenaTopoleva commented on lib/feedback_screen/feedback_screen.dart
> +        body: SingleChildScrollView(padding: EdgeInsets.all(10.0), child:
готово

2021-04-25 02:55 UTC, LenaTopoleva commented on lib/feedback_screen/feedback_screen.dart
> +        new Form(
готово

2021-04-25 02:58 UTC, LenaTopoleva commented on lib/feedback_screen/feedback_screen.dart
> +                String p = "[a-zA-Z0-9+.\_\%-+]{1,256}@[a-zA-Z0-9][a-zA-Z0-9-]{0,64}(.[a-zA-Z0-9][a-zA-Z0-9-]{0,25})+";
как я поняла, во флаттере используется TextFormField и он параметризуется как душе угодно, чтобы скрыть пароль можно добавить параметр obscureText = true, для валидации так же в параметре передается validator.

2021-04-25 02:59 UTC, LenaTopoleva commented on lib/feedback_screen/feedback_screen.dart
> +                String p = "[a-zA-Z0-9+.\_\%-+]{1,256}@[a-zA-Z0-9][a-zA-Z0-9-]{0,64}(.[a-zA-Z0-9][a-zA-Z0-9-]{0,25})+";
Я подключила официальную библиотеку с некоторыми готовыми валидаторами.

2021-04-25 03:02 UTC, LenaTopoleva commented on lib/feedback_screen/feedback_screen.dart
> +                  SnackBar(content: Text(text), backgroundColor: color,));
Да, тут был косяк. Если введенные данные не валидные, то формы подсвечиваются красным и снэкбар вообще уже не обязателен, поэтому оставила его только в случае, если все хорошо.

2021-04-25 03:26 UTC, LenaTopoleva commented on lib/schedule_screen/schedule_screen.dart
> +    if (_imageUrl != null && _imageUrl != '') image = Image.network(_imageUrl, width: 100.0, height: 100.0, fit: BoxFit.cover);
required это аннотация(потеряла @), она используется  в конструкторе, как я поняла, только в сочетании с {}, которые означают, что параметр необязательный, а когда есть слово required, то он становится "желательным". Если не передать его при создании объекта, среда подсвечивает предупреждение. Логика была такая, картинка не обязательно придет с сервера и надо подстраховаться и использовать побольше новых и непонятных аннотаций)) Наверняка хватило бы просто указания на нуллбельность, её то я, конечно, забыла поставить!

2021-04-25 16:10 UTC, LenaTopoleva commented on lib/feedback_screen/feedback_screen.dart
> +              new Text('Ваше имя:', style: TextStyle(fontSize: 20.0),),
готово

2021-04-26 13:45 UTC, LenaTopoleva commented on lib/feedback_screen/feedback_screen.dart
> +              new Text('Контактный E-mail:', style: TextStyle(fontSize: 20.0),),
готово

2021-04-26 13:46 UTC, LenaTopoleva commented on lib/feedback_screen/feedback_screen.dart
> +              new Text('Ваше имя:', style: TextStyle(fontSize: 20.0),),
готово

2021-04-26 15:59 UTC, LenaTopoleva commented on lib/schedule_screen/schedule_screen.dart
> +
готово

2021-04-26 16:02 UTC, LenaTopoleva commented on lib/schedule_screen/schedule_screen.dart
> +  ProgramListItem(this._title, this._text, this._startTime, {required String imageUrl}) {
создала класс ProgramItem, про конструктор не очень поняла. В классе ScheduleScreenState делаю маппинг List<ProgramItem> в List<ProgramListItem>

2021-04-27 09:43 UTC, closed without merging